# Generated by Django 5.1.4 on 2025-02-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_perfilusuario_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(choices=[('Relevamiento', 'Relevamiento'), ('Comisionado', 'Comisionado'), ('Implementación', 'Implementación'), ('Otro', 'Otro')], default='Otro', max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
            ],
        ),
    ]
