# Generated by Django 5.0.6 on 2025-02-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('codigo_eds', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('razon_social', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('nombre_admin', models.CharField(max_length=100)),
                ('apellidos_admin', models.CharField(max_length=100)),
                ('rut_admin', models.CharField(max_length=12, unique=True)),
                ('codigo_empresa', models.CharField(max_length=10)),
                ('verificacion_sii', models.BooleanField(default=False)),
                ('numero_cajeros', models.IntegerField()),
                ('rut_razonsocial', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('tipo_eds', models.CharField(choices=[('ASISTIDO', 'Asistido'), ('MIXTA', 'Mixta'), ('AUTOSERVICIO', 'Autoservicio')], max_length=15)),
                ('cantidad_bano', models.IntegerField()),
                ('altura_mueble', models.DecimalField(decimal_places=2, max_digits=5)),
                ('generador', models.BooleanField(default=False)),
                ('comentarios', models.TextField(max_length=2000)),
            ],
        ),
    ]
