# Generated by Django 5.0.6 on 2025-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='altura_mueble',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='cantidad_bano',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='numero_cajeros',
            field=models.CharField(max_length=2),
        ),
    ]
