# Generated by Django 5.0.6 on 2025-02-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_documento_archivo_documento_tienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/bodega/')),
            ],
        ),
        migrations.CreateModel(
            name='FotoBolleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/bolleria/')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEnchufe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/enchufes/')),
            ],
        ),
        migrations.CreateModel(
            name='FotoPantalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/pantallas/')),
            ],
        ),
        migrations.CreateModel(
            name='FotoProductoError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/productos_errores/')),
            ],
        ),
        migrations.CreateModel(
            name='FotoPuntoRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/puntos_red/')),
            ],
        ),
        migrations.CreateModel(
            name='FotoRefrigerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/refrigeradores/')),
            ],
        ),
        migrations.CreateModel(
            name='RelevamientoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_estacion_servicio', models.ImageField(blank=True, null=True, upload_to='fotos/estacion_servicio/')),
                ('video_tienda', models.FileField(blank=True, null=True, upload_to='videos/tienda/')),
                ('foto_distancia_meson_puerta', models.ImageField(blank=True, null=True, upload_to='fotos/distancia_meson_puerta/')),
                ('foto_rack', models.ImageField(blank=True, null=True, upload_to='fotos/rack/')),
                ('foto_ups', models.ImageField(blank=True, null=True, upload_to='fotos/ups/')),
                ('video_rack', models.FileField(blank=True, null=True, upload_to='videos/rack/')),
                ('foto_vista_atendedor', models.ImageField(blank=True, null=True, upload_to='fotos/vista_atendedor/')),
                ('foto_vista_cliente', models.ImageField(blank=True, null=True, upload_to='fotos/vista_cliente/')),
                ('foto_altura', models.ImageField(blank=True, null=True, upload_to='fotos/altura/')),
                ('foto_profundidad', models.ImageField(blank=True, null=True, upload_to='fotos/profundidad/')),
                ('foto_ancho', models.ImageField(blank=True, null=True, upload_to='fotos/ancho/')),
                ('foto_voltaje', models.ImageField(blank=True, null=True, upload_to='fotos/voltaje/')),
                ('foto_boleta', models.ImageField(blank=True, null=True, upload_to='fotos/boleta/')),
                ('fotos_bodega', models.ManyToManyField(blank=True, to='home.fotobodega')),
                ('fotos_bolleria', models.ManyToManyField(blank=True, to='home.fotobolleria')),
                ('fotos_enchufes', models.ManyToManyField(blank=True, to='home.fotoenchufe')),
                ('fotos_pantallas', models.ManyToManyField(blank=True, to='home.fotopantalla')),
                ('fotos_productos_errores', models.ManyToManyField(blank=True, to='home.fotoproductoerror')),
                ('fotos_puntos_red', models.ManyToManyField(blank=True, to='home.fotopuntored')),
                ('fotos_refrigeradores', models.ManyToManyField(blank=True, to='home.fotorefrigerador')),
                ('relevamiento', models.ForeignKey(limit_choices_to={'tipo_servicio': 'Relevamiento'}, on_delete=django.db.models.deletion.CASCADE, to='home.documento')),
            ],
        ),
    ]
