# Generated by Django 5.0.6 on 2025-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fotobodega_fotobolleria_fotoenchufe_fotopantalla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevamientomedia',
            name='foto_boleta',
        ),
        migrations.RemoveField(
            model_name='relevamientomedia',
            name='foto_ups',
        ),
        migrations.RemoveField(
            model_name='relevamientomedia',
            name='video_rack',
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='foto_altura',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/altura/'),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='foto_ancho',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/ancho/'),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='foto_distancia_meson_puerta',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/distancia_meson_puerta/'),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='foto_estacion_servicio',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/estacion_servicio/'),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='foto_profundidad',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/profundidad/'),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='foto_rack',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/rack/'),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='foto_vista_atendedor',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/vista_atendedor/'),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='foto_vista_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/vista_cliente/'),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='foto_voltaje',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/voltaje/'),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relevamientomedia',
            name='video_tienda',
            field=models.FileField(blank=True, null=True, upload_to='relevamiento_media/video_tienda/'),
        ),
    ]
