# Generated by Django 5.0.6 on 2025-02-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_foto_distancia_meson_puerta_1_relevamientomedia_foto_distancia_meson_puerta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_error', models.ImageField(blank=True, null=True, upload_to='relevamiento_media/errores/')),
                ('descripcion_error', models.TextField(blank=True, null=True)),
                ('fecha_error', models.DateTimeField(auto_now_add=True)),
                ('relevamiento_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='home.relevamientomedia')),
            ],
        ),
    ]
