# Generated by Django 5.0.6 on 2025-02-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_imagenerror'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenError',
        ),
    ]
