# Generated by Django 5.0.6 on 2025-02-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_imagenerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevamientomedia',
            name='foto_boleta',
            field=models.ImageField(blank=True, null=True, upload_to='relevamiento_media/estacion_servicio/'),
        ),
    ]
