# Generated by Django 5.0.6 on 2025-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_relevamientomedia_foto_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='baño_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='cantidad_pos',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='tienda',
            name='cta_tbk',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='tienda',
            name='justo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='pedidosya',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='pos_a80',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='preciodiferenciado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='rappi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tipo_tienda',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ubereats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ups_respaldo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='vuelto_mrc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='vuelto_tienda',
            field=models.BooleanField(default=False),
        ),
    ]
