# Generated by Django 5.0.6 on 2025-02-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_tienda_baño_cliente_tienda_cantidad_pos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nombre',
        ),
    ]
