# Generated by Django 5.0.6 on 2025-04-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_perfilusuario_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='altura_mueble',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='apellidos_admin',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='baño_cliente',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='cantidad_bano',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='cantidad_pos',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='generador',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='justo',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='nombre_admin',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='pedidosya',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='pos_a80',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='preciodiferenciado',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='rappi',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='rut_admin',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='tipo_tienda',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='ubereats',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='ups_respaldo',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='vuelto_mrc',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='vuelto_tienda',
        ),
        migrations.AlterField(
            model_name='tienda',
            name='numero_cajeros',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_admin', models.CharField(max_length=12, unique=True)),
                ('nombre_admin', models.CharField(max_length=100)),
                ('apellidos_admin', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubereats', models.BooleanField(default=False)),
                ('rappi', models.BooleanField(default=False)),
                ('pedidosya', models.BooleanField(default=False)),
                ('justo', models.BooleanField(default=False)),
                ('preciodiferenciado', models.BooleanField(default=False)),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_bano', models.PositiveSmallIntegerField()),
                ('altura_mueble', models.DecimalField(decimal_places=2, max_digits=5)),
                ('generador', models.BooleanField(default=False)),
                ('tipo_tienda', models.CharField(default='0', max_length=15)),
                ('vuelto_tienda', models.BooleanField(default=False)),
                ('vuelto_mrc', models.BooleanField(default=False)),
                ('pos_a80', models.BooleanField(default=False)),
                ('baño_cliente', models.BooleanField(default=False)),
                ('cantidad_pos', models.PositiveSmallIntegerField(default=0)),
                ('ups_respaldo', models.BooleanField(default=False)),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tienda')),
            ],
        ),
    ]
