# Generated by Django 5.0.6 on 2025-05-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_tienda_altura_mueble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='tipo_eds',
            field=models.CharField(max_length=15),
        ),
    ]
