# Generated by Django 5.0.6 on 2025-05-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_tienda_tipo_eds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='cta_tbk',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
