# Generated by Django 5.0.6 on 2025-05-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_tienda_cta_tbk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='preciodiferenciado',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
