# Generated by Django 5.0.6 on 2025-05-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_delivery_preciodiferenciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraestructura',
            name='vuelto_a80',
            field=models.BooleanField(default=False),
        ),
    ]
