# Generated by Django 5.0.6 on 2025-05-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_infraestructura_vuelto_a80'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraestructura',
            name='cantidad_bano',
        ),
    ]
