# Generated by Django 5.0.6 on 2025-05-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_infraestructura_cantidad_bano'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraestructura',
            name='cantidad_bano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
